#bin/bash!
sed -i 's/.1A/.1\tA/g' Ascoidea_rubescens_aa.fasta
sed -i 's/.1R/.1\tR/g' Ascoidea_rubescens_aa.fasta
sed -i 's/.1N/.1\tN/g' Ascoidea_rubescens_aa.fasta
sed -i 's/.1D/.1\tD/g' Ascoidea_rubescens_aa.fasta
sed -i 's/.1C/.1\tC/g' Ascoidea_rubescens_aa.fasta
sed -i 's/.1Q/.1\tQ/g' Ascoidea_rubescens_aa.fasta
sed -i 's/.1E/.1\tE/g' Ascoidea_rubescens_aa.fasta
sed -i 's/.1G/.1\tG/g' Ascoidea_rubescens_aa.fasta
sed -i 's/.1H/.1\tH/g' Ascoidea_rubescens_aa.fasta
sed -i 's/.1I/.1\tI/g' Ascoidea_rubescens_aa.fasta
sed -i 's/.1L/.1\tL/g' Ascoidea_rubescens_aa.fasta
sed -i 's/.1K/.1\tK/g' Ascoidea_rubescens_aa.fasta
sed -i 's/.1M/.1\tM/g' Ascoidea_rubescens_aa.fasta
sed -i 's/.1F/.1\tF/g' Ascoidea_rubescens_aa.fasta
sed -i 's/.1P/.1\tP/g' Ascoidea_rubescens_aa.fasta
sed -i 's/.1S/.1\tS/g' Ascoidea_rubescens_aa.fasta
sed -i 's/.1T/.1\tT/g' Ascoidea_rubescens_aa.fasta
sed -i 's/.1W/.1\tW/g' Ascoidea_rubescens_aa.fasta
sed -i 's/.1V/.1\tV/g' Ascoidea_rubescens_aa.fasta
sed -i 's/.1Y/.1\tY/g' Ascoidea_rubescens_aa.fasta
