sed -i "s/Aaoar1/Aaosphaeria_arxii/g"  *.fasta
sed -i "s/Altbr1/Alternaria_brassicicola/g" *.fasta
sed -i "s/Ambph1/Ambrosiozyma_philentoma/g" *.fasta
sed -i "s/Amnli1/Amniculicola_lignicola/g" *.fasta
sed -i "s/Amore1/Amorphotheca_resinae/g" *.fasta
sed -i "s/Ampqu1/Ampelomyces_quisqualis/g" *.fasta
sed -i "s/Aplpr1/Aplosporella_prunicola/g" *.fasta
sed -i "s/Artol1/Arthrobotrys_oligospora/g" *.fasta
sed -i "s/Artbe1/Arthroderma_benhamiae/g" *.fasta
sed -i "s/Ascim1/Ascobolus_immersus/g" *.fasta
sed -i "s/Ascra1/Ascochyta_rabiei/g" *.fasta
sed -i "s/Ascsa1/Ascocoryne_sarcoides/g" *.fasta
sed -i "s/Ascni1/Ascodesmis_nigricans/g" *.fasta
sed -i "s/Ascru1/Ascoidea_rubescens/g" *.fasta
sed -i "s/Aspni1/Aspergillus_nidulans/g" *.fasta
sed -i "s/Aulhe1/Aulographum_hederae/g" *.fasta
sed -i "s/Babin1/Babjeviella_inositovora/g" *.fasta
sed -i "s/Bauco1/Baudoinia_compniacensis/g" *.fasta
sed -i "s/Beaba1/Beauveria_bassiana/g" *.fasta
sed -i "s/Bimno1/Bimuria_novae-zelandiae/g" *.fasta
sed -i "s/Blaad1/Blastobotrys_adeninivorans/g" *.fasta
sed -i "s/Blade1/Blastomyces_dermatitidis/g" *.fasta
sed -i "s/Blugr1/Blumeria_graminis_f._sp._tritici/g" *.fasta
sed -i "s/Botdo1/Botryosphaeria_dothidea/g" *.fasta
sed -i "s/Botci1/Botrytis_cinerea/g" *.fasta
sed -i "s/Byssp1/Byssochlamys_spectabilis/g" *.fasta
sed -i "s/Bysci1/Byssothecium_circinans/g" *.fasta
sed -i "s/Cadsp1/Cadophora_sp._DSE1049/g" *.fasta
sed -i "s/Canal1/Candida_albicans/g" *.fasta
sed -i "s/Capco1/Capronia_coronata/g" *.fasta
sed -i "s/Capep1/Capronia_epimyces/g" *.fasta
sed -i "s/Capse1/Capronia_semiimmersa/g" *.fasta
sed -i "s/Cenge1/Cenococcum_geophilum/g" *.fasta
sed -i "s/Cerze1/Cercospora_zeae-maydis/g" *.fasta
sed -i "s/Chagl1/Chaetomium_globosum/g" *.fasta
sed -i "s/Chath1/Chaetomium_thermophilum_var_thermophilum/g" *.fasta
sed -i "s/Chalo1/Chalara_longipes/g" *.fasta
sed -i "s/Chove1/Choiromyces_venosus/g" *.fasta
sed -i "s/Citma1/Citeromyces_matritensis/g" *.fasta
sed -i "s/Clagr1/Cladonia_grayi/g" *.fasta
sed -i "s/Clafu1/Cladosporium_fulvum/g" *.fasta
sed -i "s/Clael1/Clathrospora_elynae/g" *.fasta
sed -i "s/Clalu1/Clavispora_lusitaniae/g" *.fasta
sed -i "s/Cloaq1/Clohesyomyces_aquaticus/g" *.fasta
sed -i "s/Cocim1/Coccidioides_immitis/g" *.fasta
sed -i "s/Cocpo1/Coccidioides_posadasii/g" *.fasta
sed -i "s/Coche1/Cochliobolus_heterostrophus/g" *.fasta
sed -i "s/Colgr1/Colletotrichum_graminicola/g" *.fasta
sed -i "s/Cucbe1/Cucurbitaria_berberidis/g" *.fasta
sed -i "s/Cypeu1/Cyphellophora_europaea/g" *.fasta
sed -i "s/Dales1/Daldinia_eschscholtzii/g" *.fasta
sed -i "s/Debha1/Debaryomyces_hansenii/g" *.fasta
sed -i "s/Decga1/Decorospora_gaudefroyi/g" *.fasta
sed -i "s/Dekbr1/Dekkera_bruxellensis/g" *.fasta
sed -i "s/Delco1/Delitschia_confertaspora/g" *.fasta
sed -i "s/Delst1/Delphinella_strobiligena/g" *.fasta
sed -i "s/Diaam1/Diaporthe_ampelina/g" *.fasta
sed -i "s/Didex1/Didymella_exigua/g" *.fasta
sed -i "s/Dipse1/Diplodia_seriata/g" *.fasta
sed -i "s/Disac1/Dissoconium_aciculare/g" *.fasta
sed -i "s/Dotsy1/Dothidotthia_symphoricarpi/g" *.fasta
sed -i "s/Dotse1/Dothistroma_septosporum/g" *.fasta
sed -i "s/Elsam1/Elsinoe_ampelina/g" *.fasta
sed -i "s/Endpu1/Endocarpon_pusillum/g" *.fasta
sed -i "s/Erebi1/Eremomyces_bilateralis/g" *.fasta
sed -i "s/Erego1/Eremothecium_gossypii/g" *.fasta
sed -i "s/Eryne1/Erysiphe_necator/g" *.fasta
sed -i "s/Escwe1/Escovopsis_weberi/g" *.fasta
sed -i "s/Eurru1/Eurotium_rubrum/g" *.fasta
sed -i "s/Eutla1/Eutypa_lata/g" *.fasta
sed -i "s/Exode1/Exophiala_dermatitidis/g" *.fasta
sed -i "s/Fonpe1/Fonsecaea_pedrosoi/g" *.fasta
sed -i "s/Fusgr1/Fusarium_graminearum/g" *.fasta
sed -i "s/Gaegr1/Gaeumannomyces_graminis_var._tritici/g" *.fasta
sed -i "s/Glalo1/Glarea_lozoyensis/g" *.fasta
sed -i "s/Glost1/Glonium_stellatum/g" *.fasta
sed -i "s/Grocl1/Grosmannia_clavigera/g" *.fasta
sed -i "s/Hangu1/Hanseniaspora_guilliermondii/g" *.fasta
sed -i "s/Hisca1/Histoplasma_capsulatum/g" *.fasta
sed -i "s/Horwe1/Hortaea_werneckii/g" *.fasta
sed -i "s/Hypbu1/Hyphopichia_burtonii/g" *.fasta
sed -i "s/Hypsp1/Hypoxylon_sp./g" *.fasta
sed -i "s/Hyspu1/Hysterium_pulicare/g" *.fasta
sed -i "s/Ilysp1/Ilyonectria_sp./g" *.fasta
sed -i "s/Kalpf1/Kalaharituber_pfeilii/g" *.fasta
sed -i "s/Karrh1/Karstenula_rhodostoma/g" *.fasta
sed -i "s/Kazaf1/Kazachstania_africana/g" *.fasta
sed -i "s/Klula1/Kluyveromyces_lactis/g" *.fasta
sed -i "s/Kurca1/Kuraishia_capsulata/g" *.fasta
sed -i "s/Lacqu1/Lachancea_quebecensis/g" *.fasta
sed -i "s/Lenfl1/Lentithecium_fluviatile/g" *.fasta
sed -i "s/Leppa1/Lepidopterella_palustris/g" *.fasta
sed -i "s/Lepma1/Leptosphaeria_maculans/g" *.fasta
sed -i "s/Linin1/Lindgomyces_ingoldianus/g" *.fasta
sed -i "s/Linrh1/Lineolata_rhizophorae/g" *.fasta
sed -i "s/Lipst1/Lipomyces_starkeyi/g" *.fasta
sed -i "s/Lizem1/Lizonia_empirigonia/g" *.fasta
sed -i "s/Lodel1/Lodderomyces_elongisporus/g" *.fasta
sed -i "s/Lopma1/Lophiostoma_macrostomum/g" *.fasta
sed -i "s/Lopnu1/Lophiotrema_nucula/g" *.fasta
sed -i "s/Lopmy1/Lophium_mytilinum/g" *.fasta
sed -i "s/Macph1/Macrophomina_phaseolina/g" *.fasta
sed -i "s/Macan1/Macroventuria_anomochaeta/g" *.fasta
sed -i "s/Madmy1/Madurella_mycetomatis/g" *.fasta
sed -i "s/Magor1/Magnaporthe_oryzae/g" *.fasta
sed -i "s/Magpo1/Magnaporthiopsis_poae/g" *.fasta
sed -i "s/Marbr1/Marssonina_brunnea_f._sp._multigermtubi/g" *.fasta
sed -i "s/Maseb1/Massarina_eburnea/g" *.fasta
sed -i "s/Masph1/Massariosphaeria_phaeospora/g" *.fasta
sed -i "s/Melpu1/Melanomma_pulvis-pyrius/g" *.fasta
sed -i "s/Melva1/Meliniomyces_variabilis/g" *.fasta
sed -i "s/Metac1/Metarhizium_acridum/g" *.fasta
sed -i "s/Metfr1/Metschnikowia_fructicola/g" *.fasta
sed -i "s/Meygu1/Meyerozyma_guilliermondii/g" *.fasta
sed -i "s/Micbo1/Microdochium_bolleyi/g" *.fasta
sed -i "s/Micca1/Microsporum_canis/g" *.fasta
sed -i "s/Micmi1/Microthyrium_microscopicum/g" *.fasta
sed -i "s/Monha1/Monacrosporium_haptotylum/g" *.fasta
sed -i "s/Morim1/Morchella_importuna/g" *.fasta
sed -i "s/Mycth1/Myceliophthora_thermophila/g" *.fasta
sed -i "s/Mycgr1/Mycosphaerella_graminicola/g" *.fasta
sed -i "s/Myrdu1/Myriangium_duriaei *.fasta
sed -i "s/Mytre1/Mytilinidion_resinicola/g" *.fasta
sed -i "s/Nadfu1/Nadsonia_fulvescens_var._elongata/g" *.fasta
sed -i "s/Nakde1/Nakaseomyces_delphensis/g" *.fasta
sed -i "s/Nakwi1/Nakazawaea_wickerhamii/g" *.fasta
sed -i "s/Nauca1/Naumovozyma_castellii/g" *.fasta
sed -i "s/Necha1/Nectria_haematococca/g" *.fasta
sed -i "s/Neopa1/Neofusicoccum_parvum/g" *.fasta
sed -i "s/Neoir1/Neolecta_irregularis/g" *.fasta
sed -i "s/Neodi1/Neonectria_ditissima/g" *.fasta
sed -i "s/Neofi1/Neosartorya_fischeri/g" *.fasta
sed -i "s/Neucr1/Neurospora_crassa/g" *.fasta
sed -i "s/Ogapo1/Ogataea_polymorpha/g" *.fasta
sed -i "s/Oidma1/Oidiodendron_maius/g" *.fasta
sed -i "s/Ophdi1/Ophiobolus_disseminans/g" *.fasta
sed -i "s/Ophpi1/Ophiostoma_piceae/g" *.fasta
sed -i "s/Pacta1/Pachysolen_tannophilus/g" *.fasta
sed -i "s/Paeva1/Paecilomyces_variotii/g" *.fasta
sed -i "s/Parbr1/Paracoccidioides_brasiliensis/g" *.fasta
sed -i "s/Parsp1/Paraconiothyrium_sporulosum/g" *.fasta
sed -i "s/Patat1/Patellaria_atrata/g" *.fasta
sed -i "s/Pench1/Penicillium_chrysogenum/g" *.fasta
sed -i "s/Perma1/Periconia_macrospinosa/g" *.fasta
sed -i "s/Pesfi1/Pestalotiopsis_fici/g" *.fasta
sed -i "s/Petxy1/Peterozyma_xylosa_NRRL/g" *.fasta
sed -i "s/Phaal1/Phaeoacremonium_aleophilum/g" *.fasta
sed -i "s/Phach1/Phaeomoniella_chlamydospora/g" *.fasta
sed -i "s/Phisc1/Phialocephala_scopiformis/g" *.fasta
sed -i "s/Phiat1/Phialophora_attae/g" *.fasta
sed -i "s/Photr1/Phoma_tracheiphila/g" *.fasta
sed -i "s/Phyci1/Phyllosticta_citricarpa/g" *.fasta
sed -i "s/Picpa1/Pichia_pastoris/g" *.fasta
sed -i "s/Pieho1/Piedraia_hortae/g" *.fasta
sed -i "s/Plesi1/Pleomassaria_siparia/g" *.fasta
sed -i "s/Pneji1/Pneumocystis_jirovecii/g" *.fasta
sed -i "s/Pocch1/Pochonia_chlamydosporia/g" *.fasta
sed -i "s/Podan1/Podospora_anserina/g" *.fasta
sed -i "s/Polci1/Polychaeton_citri/g" *.fasta
sed -i "s/Polfu1/Polyplosphaeria_fusca/g" *.fasta
sed -i "s/Prola1/Protomyces_lactucaedebilis/g" *.fasta
sed -i "s/Psefi1/Pseudocercospora_(Mycosphaerella)_fijiensis/g" *.fasta
sed -i "s/Psede1/Pseudogymnoascus_destructans/g" *.fasta
sed -i "s/Pseve1/Pseudomassariella_vexata/g" *.fasta
sed -i "s/Psehy1/Pseudovirgaria_hyperparasitica/g" *.fasta
sed -i "s/Pyrsp1/Pyrenochaeta_sp./g" *.fasta
sed -i "s/Pyrtr1/Pyrenophora_tritici-repentis/g" *.fasta
sed -i "s/Rhima1/Rhinocladiella_mackenziei/g" *.fasta
sed -i "s/Rhili1/Rhizodiscina_lignyota/g" *.fasta
sed -i "s/Rhier1/Rhizoscyphus_ericae/g" *.fasta
sed -i "s/Rhyse1/Rhynchosporium_secalis/g" *.fasta
sed -i "s/Rhyru1/Rhytidhysteron_rufulum/g" *.fasta
sed -i "s/Rosne1/Rosellinia_necatrix/g" *.fasta
sed -i "s/Sacpr1/Saccharata_proteae/g" *.fasta
sed -i "s/Sacce1/Saccharomyces_cerevisiae/g" *.fasta
sed -i "s/Sacca1/Saccharomycopsis_capsularis/g" *.fasta
sed -i "s/Saico1/Saitoella_complicata/g" *.fasta
sed -i "s/Satdi1/Saturnispora_dispora/g" *.fasta
sed -i "s/Schst1/Scheffersomyces_stipitis/g" *.fasta
sed -i "s/Schpo1/Schizosaccharomyces_pombe/g" *.fasta
sed -i "s/Sclsc1/Sclerotinia_sclerotiorum/g" *.fasta
sed -i "s/Sepmu1/Septoria_musiva/g" *.fasta
sed -i "s/Seppo1/Septoria_populicola/g" *.fasta
sed -i "s/Setho1/Setomelanomma_holmii/g" *.fasta
sed -i "s/Settu1/Setosphaeria_turcica_Et28A_v2.0/g" *.fasta
sed -i "s/Sodal1/Sodiomyces_alkalinus/g" *.fasta
sed -i "s/Sorma1/Sordaria_macrospora/g" *.fasta
sed -i "s/Spapa1/Spathaspora_passalidarum/g" *.fasta
sed -i "s/Sphbr1/Sphaerosporella_brunnea/g" *.fasta
sed -i "s/Spofi1/Sporormia_fimetaria/g" *.fasta
sed -i "s/Stano1/Stagonospora_nodorum/g" *.fasta
sed -i "s/Stely1/Stemphylium_lycopersici/g" *.fasta
sed -i "s/Talbo1/Talaromyces_borbonicus/g" *.fasta
sed -i "s/Talst1/Talaromyces_stipitatus/g" *.fasta
sed -i "s/Tapde1/Taphrina_deformans/g" *.fasta
sed -i "s/Ternu1/Teratosphaeria_nubilosa/g" *.fasta
sed -i "s/Tercl1/Terfezia_claveryi/g" *.fasta
sed -i "s/Tetph1/Tetrapisispora_phaffii/g" *.fasta
sed -i "s/Thela1/Thermomyces_lanuginosus/g" *.fasta
sed -i "s/Thite1/Thielavia_terrestris/g" *.fasta
sed -i "s/Tirni1/Tirmania_nivea/g" *.fasta
sed -i "s/Tolin1/Tolypocladium_inflatum/g" *.fasta
sed -i "s/Torca1/Tortispora_caseinolytica/g" *.fasta
sed -i "s/Torde1/Torulaspora_delbrueckii/g" *.fasta
sed -i "s/Totfu1/Tothia_fuscella/g" *.fasta
sed -i "s/Trepe1/Trematosphaeria_pertusa/g" *.fasta
sed -i "s/Trire1/Trichoderma_reesei/g" *.fasta
sed -i "s/Trihy1/Trichophaea_hybrida/g" *.fasta
sed -i "s/Trive1/Trichophyton_verrucosum/g" *.fasta
sed -i "s/Tubae1/Tuber_aestivum_var._urcinatum/g" *.fasta
sed -i "s/Uncre1/Uncinocarpus_reesii/g" *.fasta
sed -i "s/Ustvi1/Ustilaginoidea_virens/g" *.fasta
sed -i "s/Vanpo1/Vanderwaltozyma_polyspora/g" *.fasta
sed -i "s/Venef1/Venturia_effusa/g" *.fasta
sed -i "s/Verga1/Verruconis_gallopava/g" *.fasta
sed -i "s/Veren1/Verruculina_enalia/g" *.fasta
sed -i "s/Veral1/Verticillium_alfalfae/g" *.fasta
sed -i "s/Virvi1/Viridothelium_virens/g" *.fasta
sed -i "s/Wesor1/Westerdykella_ornata/g" *.fasta
sed -i "s/Wicso1/Wickerhamiella_sorbophila/g" *.fasta
sed -i "s/Wican1/Wickerhamomyces_anomalus/g" *.fasta
sed -i "s/Wilmi1/Wilcoxina_mikolae/g" *.fasta
sed -i "s/Yarli1/Yarrowia_lipolytica/g" *.fasta
sed -i "s/Zasce1/Zasmidium_cellare/g" *.fasta
sed -i "s/Zoprh1/Zopfia_rhizophila/g" *.fasta
sed -i "s/Zygro1/Zygosaccharomyces_rouxii/g" *.fasta
