sed -i "s/Aaoar1/Aaosphaeria_arxii_CBS_175.79_v1.0/g"  *.fasta
sed -i "s/Altbr1/Alternaria_brassicicola/g" *.fasta
sed -i "s/Ambph1/Ambrosiozyma_philentoma_NRRL_Y-7523/g" *.fasta
sed -i "s/Amnli1/Amniculicola_lignicola_CBS_123094_v1.0/g" *.fasta
sed -i "s/Amore1/Amorphotheca_resinae_v1.0/g" *.fasta
sed -i "s/Ampqu1/Ampelomyces_quisqualis_HMLAC05119_v1.0/g" *.fasta
sed -i "s/Aplpr1/Aplosporella_prunicola_CBS_121.167_v1.0/g" *.fasta
sed -i "s/Artol1/Arthrobotrys_oligospora_ATCC_24927/g" *.fasta
sed -i "s/Artbe1/Arthroderma_benhamiae_CBS_112371/g" *.fasta
sed -i "s/Ascim1/Ascobolus_immersus_RN42_v1.0/g" *.fasta
sed -i "s/Ascra1/Ascochyta_rabiei_ArDII/g" *.fasta
sed -i "s/Ascsa1/Ascocoryne_sarcoides_NRRL50072/g" *.fasta
sed -i "s/Ascni1/Ascodesmis_nigricans_CBS_389.68_v1.0/g" *.fasta
sed -i "s/Ascru1/Ascoidea_rubescens_NRRL_Y17699_v1.0/g" *.fasta
sed -i "s/Aspni1/Aspergillus_nidulans/g" *.fasta
sed -i "s/Aulhe1/Aulographum_hederae_v2.0/g" *.fasta
sed -i "s/Babin1/Babjeviella_inositovora_NRRL_Y-12698_v1.0/g" *.fasta
sed -i "s/Bauco1/Baudoinia_compniacensis_UAMH_10762_(4089826)_v1.0/g" *.fasta
sed -i "s/Beaba1/Beauveria_bassiana_ARSEF_2860/g" *.fasta
sed -i "s/Bimno1/Bimuria_novae-zelandiae_CBS_107.79_v1.0/g" *.fasta
sed -i "s/Blaad1/Blastobotrys_(Arxula)_adeninivorans/g" *.fasta
sed -i "s/Blade1/Blastomyces_dermatitidis_SLH14081/g" *.fasta
sed -i "s/Blugr1/Blumeria_graminis_f._sp._tritici_96224_v3.16/g" *.fasta
sed -i "s/Botdo1/Botryosphaeria_dothidea/g" *.fasta
sed -i "s/Botci1/Botrytis_cinerea_v1.0/g" *.fasta
sed -i "s/Byssp1/Byssochlamys_spectabilis_No._5/g" *.fasta
sed -i "s/Bysci1/Byssothecium_circinans_CBS_675.92_v1.0/g" *.fasta
sed -i "s/Cadsp1/Cadophora_sp._DSE1049_v1.0/g" *.fasta
sed -i "s/Canal1/Candida_albicans_SC5314/g" *.fasta
sed -i "s/Capco1/Capronia_coronata_CBS_617.96/g" *.fasta
sed -i "s/Capep1/Capronia_epimyces_CBS_606.96/g" *.fasta
sed -i "s/Capse1/Capronia_semiimmersa_CBS27337/g" *.fasta
sed -i "s/Cenge1/Cenococcum_geophilum_1.58_v2.0/g" *.fasta
sed -i "s/Cerze1/Cercospora_zeae-maydis_v1.0/g" *.fasta
sed -i "s/Chagl1/Chaetomium_globosum_v1.0/g" *.fasta
sed -i "s/Chath1/Chaetomium_thermophilum_var_thermophilum_DSM_1495/g" *.fasta
sed -i "s/Chalo1/Chalara_longipes_BDJ_v1.0/g" *.fasta
sed -i "s/Chove1/Choiromyces_venosus_120613-1_v1.0/g" *.fasta
sed -i "s/Citma1/Citeromyces_matritensis_NRRL_Y-2407/g" *.fasta
sed -i "s/Clagr1/Cladonia_grayi_Cgr/DA2myc/ss_v2.0/g" *.fasta
sed -i "s/Clafu1/Cladosporium_fulvum_v1.0/g" *.fasta
sed -i "s/Clael1/Clathrospora_elynae_CBS_161.51_v1.0/g" *.fasta
sed -i "s/Clalu1/Clavispora_lusitaniae_ATCC_42720/g" *.fasta
sed -i "s/Cloaq1/Clohesyomyces_aquaticus_v1.0/g" *.fasta
sed -i "s/Cocim1/Coccidioides_immitis_Rs/g" *.fasta
sed -i "s/Cocpo1/Coccidioides_posadasii_C735_delta_SOWgp/g" *.fasta
sed -i "s/Coche1/Cochliobolus_heterostrophus_C5_v2.0/g" *.fasta
sed -i "s/Colgr1/Colletotrichum_graminicola_M1.001/g" *.fasta
sed -i "s/Cucbe1/Cucurbitaria_berberidis_CBS_394.84_v1.0/g" *.fasta
sed -i "s/Cypeu1/Cyphellophora_europaea_CBS_101466/g" *.fasta
sed -i "s/Dales1/Daldinia_eschscholtzii_EC12_v1.0/g" *.fasta
sed -i "s/Debha1/Debaryomyces_hansenii/g" *.fasta
sed -i "s/Decga1/Decorospora_gaudefroyi_v1.0/g" *.fasta
sed -i "s/Dekbr1/Dekkera_bruxellensis_CBS_2499_v2.0/g" *.fasta
sed -i "s/Delco1/Delitschia_confertaspora_ATCC_74209_v1.0/g" *.fasta
sed -i "s/Delst1/Delphinella_strobiligena_CBS_735.71_v1.0/g" *.fasta
sed -i "s/Diaam1/Diaporthe_ampelina_UCDDA912/g" *.fasta
sed -i "s/Didex1/Didymella_exigua_CBS_183.55_v1.0/g" *.fasta
sed -i "s/Dipse1/Diplodia_seriata_DS831/g" *.fasta
sed -i "s/Disac1/Dissoconium_aciculare_v1.0/g" *.fasta
sed -i "s/Dotsy1/Dothidotthia_symphoricarpi_v1.0/g" *.fasta
sed -i "s/Dotse1/Dothistroma_septosporum_NZE10_v1.0/g" *.fasta
sed -i "s/Elsam1/Elsinoe_ampelina_CECT_20119_v1.0/g" *.fasta
sed -i "s/Endpu1/Endocarpon_pusillum_Z07020/g" *.fasta
sed -i "s/Erebi1/Eremomyces_bilateralis_CBS_781.70_v1.0/g" *.fasta
sed -i "s/Erego1/Eremothecium_gossypii_ATCC_10895/g" *.fasta
sed -i "s/Eryne1/Erysiphe_necator_c/g" *.fasta
sed -i "s/Escwe1/Escovopsis_weberi_CC031208-10/g" *.fasta
sed -i "s/Eurru1/Eurotium_rubrum_v1.0/g" *.fasta
sed -i "s/Eutla1/Eutypa_lata_UCREL1/g" *.fasta
sed -i "s/Exode1/Exophiala_dermatitidis_UT8656/g" *.fasta
sed -i "s/Fonpe1/Fonsecaea_pedrosoi_CBS_271.37/g" *.fasta
sed -i "s/Fusgr1/Fusarium_graminearum_v1.0/g" *.fasta
sed -i "s/Gaegr1/Gaeumannomyces_graminis_var._tritici_R3-111a-1/g" *.fasta
sed -i "s/Glalo1/Glarea_lozoyensis_ATCC_20868/g" *.fasta
sed -i "s/Glost1/Glonium_stellatum_CBS_207.34_v1.0/g" *.fasta
sed -i "s/Grocl1/Grosmannia_clavigera_kw1407/g" *.fasta
sed -i "s/Hangu1/Hanseniaspora_guilliermondii_UTAD222/g" *.fasta
sed -i "s/Hisca1/Histoplasma_capsulatum_NAm1/g" *.fasta
sed -i "s/Horwe1/Hortaea_werneckii_EXF-2000_M0_v1.0/g" *.fasta
sed -i "s/Hypbu1/Hyphopichia_burtonii_NRRL_Y-1933_v1.0/g" *.fasta
sed -i "s/Hypsp1/Hypoxylon_sp._EC38_v3.0/g" *.fasta
sed -i "s/Hyspu1/Hysterium_pulicare/g" *.fasta
sed -i "s/Ilysp1/Ilyonectria_sp._v1.0/g" *.fasta
sed -i "s/Kalpf1/Kalaharituber_pfeilii_F3_v1.0/g" *.fasta
sed -i "s/Karrh1/Karstenula_rhodostoma_CBS_690.94_v1.0/g" *.fasta
sed -i "s/Kazaf1/Kazachstania_africana_CBS_2517/g" *.fasta
sed -i "s/Klula1/Kluyveromyces_lactis/g" *.fasta
sed -i "s/Kurca1/Kuraishia_capsulata_CBS_1993/g" *.fasta
sed -i "s/Lacqu1/Lachancea_quebecensis_INRA_UMR_1319/g" *.fasta
sed -i "s/Lenfl1/Lentithecium_fluviatile_v1.0/g" *.fasta
sed -i "s/Leppa1/Lepidopterella_palustris_v1.0/g" *.fasta
sed -i "s/Lepma1/Leptosphaeria_maculans/g" *.fasta
sed -i "s/Linin1/Lindgomyces_ingoldianus_ATCC_200398_v1.0/g" *.fasta
sed -i "s/Linrh1/Lineolata_rhizophorae_ATCC_16933_v1.0/g" *.fasta
sed -i "s/Lipst1/Lipomyces_starkeyi_NRRL_Y-11557_v1.0/g" *.fasta
sed -i "s/Lizem1/Lizonia_empirigonia_CBS_542.76_v1.0/g" *.fasta
sed -i "s/Lodel1/Lodderomyces_elongisporus_NRRL_YB-4239/g" *.fasta
sed -i "s/Lopma1/Lophiostoma_macrostomum_v1.0/g" *.fasta
sed -i "s/Lopnu1/Lophiotrema_nucula_CBS_627.86_v1.0/g" *.fasta
sed -i "s/Lopmy1/Lophium_mytilinum_CBS_269.34_v1.0/g" *.fasta
sed -i "s/Macph1/Macrophomina_phaseolina_MS6/g" *.fasta
sed -i "s/Macan1/Macroventuria_anomochaeta_CBS_525.71_v1.0/g" *.fasta
sed -i "s/Madmy1/Madurella_mycetomatis_mm55/g" *.fasta
sed -i "s/Magor1/Magnaporthe_oryzae_70-15_v3.0/g" *.fasta
sed -i "s/Magpo1/Magnaporthiopsis_poae_ATCC_64411/g" *.fasta
sed -i "s/Marbr1/Marssonina_brunnea_f._sp._multigermtubi_MB_m1/g" *.fasta
sed -i "s/Maseb1/Massarina_eburnea_CBS_473.64_v1.0/g" *.fasta
sed -i "s/Masph1/Massariosphaeria_phaeospora_CBS_611.86_v1.0/g" *.fasta
sed -i "s/Melpu1/Melanomma_pulvis-pyrius_v1.0/g" *.fasta
sed -i "s/Melva1/Meliniomyces_variabilis_F_v1.0/g" *.fasta
sed -i "s/Metac1/Metarhizium_acridum_CQMa_102/g" *.fasta
sed -i "s/Metfr1/Metschnikowia_fructicola_277/g" *.fasta
sed -i "s/Meygu1/Meyerozyma_guilliermondii_ATCC_6260/g" *.fasta
sed -i "s/Micbo1/Microdochium_bolleyi_J235TASD1_v1.0/g" *.fasta
sed -i "s/Micca1/Microsporum_canis_CBS_113480/g" *.fasta
sed -i "s/Micmi1/Microthyrium_microscopicum_CBS_115976_v1.0/g" *.fasta
sed -i "s/Monha1/Monacrosporium_haptotylum_CBS_200.50/g" *.fasta
sed -i "s/Morim1/Morchella_importuna_SCYDJ1-A1_v1.0/g" *.fasta
sed -i "s/Mycth1/Myceliophthora_thermophila_(Sporotrichum_thermophile)_v2.0/g" *.fasta
sed -i "s/Mycgr1/Mycosphaerella_graminicola_v2.0/g" *.fasta
sed -i "s/Myrdu1/Myriangium_duriaei_CBS_260.36_v1.0/g" *.fasta
sed -i "s/Mytre1/Mytilinidion_resinicola_CBS_304.34_v1.0/g" *.fasta
sed -i "s/Nadfu1/Nadsonia_fulvescens_var._elongata_DSM_6958_v1.0/g" *.fasta
sed -i "s/Nakde1/Nakaseomyces_delphensis_CBS_2170/g" *.fasta
sed -i "s/Nakwi1/Nakazawaea_wickerhamii_NRRL_Y-2563/g" *.fasta
sed -i "s/Nauca1/Naumovozyma_castellii_CBS_4309/g" *.fasta
sed -i "s/Necha1/Nectria_haematococca_v2.0/g" *.fasta
sed -i "s/Neopa1/Neofusicoccum_parvum_UCRNP2/g" *.fasta
sed -i "s/Neoir1/Neolecta_irregularis_DAH-1_v1.0/g" *.fasta
sed -i "s/Neodi1/Neonectria_ditissima_R09/05/g" *.fasta
sed -i "s/Neofi1/Neosartorya_fischeri_NRRL_181/g" *.fasta
sed -i "s/Neucr1/Neurospora_crassa_FGSC_73_trp-3_v1.0/g" *.fasta
sed -i "s/Ogapo1/Ogataea_polymorpha_NCYC_495_leu1.1_v2.0/g" *.fasta
sed -i "s/Oidma1/Oidiodendron_maius_Zn_v1.0/g" *.fasta
sed -i "s/Ophdi1/Ophiobolus_disseminans_CBS_113818_v1.0/g" *.fasta
sed -i "s/Ophpi1/Ophiostoma_piceae_UAMH_11346/g" *.fasta
sed -i "s/Pacta1/Pachysolen_tannophilus_NRRL_Y-2460_v1.2/g" *.fasta
sed -i "s/Paeva1/Paecilomyces_variotii_CBS_101075_v1.0/g" *.fasta
sed -i "s/Parbr1/Paracoccidioides_brasiliensis_Pb18/g" *.fasta
sed -i "s/Parsp1/Paraconiothyrium_sporulosum_AP3s5-JAC2a_v1.0/g" *.fasta
sed -i "s/Patat1/Patellaria_atrata_v1.0/g" *.fasta
sed -i "s/Pench1/Penicillium_chrysogenum_v1.0/g" *.fasta
sed -i "s/Perma1/Periconia_macrospinosa_DSE2036_v1.0/g" *.fasta
sed -i "s/Pesfi1/Pestalotiopsis_fici_W106-1/g" *.fasta
sed -i "s/Petxy1/Peterozyma_xylosa_NRRL_Y-12939/g" *.fasta
sed -i "s/Phaal1/Phaeoacremonium_aleophilum_UCRPA7/g" *.fasta
sed -i "s/Phach1/Phaeomoniella_chlamydospora_UCRPC4/g" *.fasta
sed -i "s/Phisc1/Phialocephala_scopiformis_5WS22E1_v1.0/g" *.fasta
sed -i "s/Phiat1/Phialophora_attae_CBS_131958/g" *.fasta
sed -i "s/Photr1/Phoma_tracheiphila_IPT5_v1.0/g" *.fasta
sed -i "s/Phyci1/Phyllosticta_citricarpa_CBS_127454_v1.0/g" *.fasta
sed -i "s/Picpa1/Pichia_pastoris/g" *.fasta
sed -i "s/Pieho1/Piedraia_hortae_CBS_480.64_v1.1/g" *.fasta
sed -i "s/Plesi1/Pleomassaria_siparia_v1.0/g" *.fasta
sed -i "s/Pneji1/Pneumocystis_jirovecii/g" *.fasta
sed -i "s/Pocch1/Pochonia_chlamydosporia_170/g" *.fasta
sed -i "s/Podan1/Podospora_anserina_S_mat+/g" *.fasta
sed -i "s/Polci1/Polychaeton_citri_v1.0/g" *.fasta
sed -i "s/Polfu1/Polyplosphaeria_fusca_CBS_125425_v1.0/g" *.fasta
sed -i "s/Prola1/Protomyces_lactucaedebilis_12-1054_v1.0/g" *.fasta
sed -i "s/Psefi1/Pseudocercospora_(Mycosphaerella)_fijiensis_v2.0/g" *.fasta
sed -i "s/Psede1/Pseudogymnoascus_destructans_20631-21/g" *.fasta
sed -i "s/Pseve1/Pseudomassariella_vexata_CBS_129021_v1.0/g" *.fasta
sed -i "s/Psehy1/Pseudovirgaria_hyperparasitica_CBS_121739_v1.0/g" *.fasta
sed -i "s/Pyrsp1/Pyrenochaeta_sp._DS3sAY3a_v1.0/g" *.fasta
sed -i "s/Pyrtr1/Pyrenophora_tritici-repentis/g" *.fasta
sed -i "s/Rhima1/Rhinocladiella_mackenziei_CBS_650.93/g" *.fasta
sed -i "s/Rhili1/Rhizodiscina_lignyota_CBS_133067_v1.0/g" *.fasta
sed -i "s/Rhier1/Rhizoscyphus_ericae_UAMH_7357_v1.0/g" *.fasta
sed -i "s/Rhyse1/Rhynchosporium_secalis_02CH4_6a1/g" *.fasta
sed -i "s/Rhyru1/Rhytidhysteron_rufulum/g" *.fasta
sed -i "s/Rosne1/Rosellinia_necatrix_W97/g" *.fasta
sed -i "s/Sacpr1/Saccharata_proteae_CBS_121410_v1.0/g" *.fasta
sed -i "s/Sacce1/Saccharomyces_cerevisiae_M3838_v1.0/g" *.fasta
sed -i "s/Sacca1/Saccharomycopsis_capsularis_NRRL_Y-17639/g" *.fasta
sed -i "s/Saico1/Saitoella_complicata_NRRL_Y-17804_v1.0/g" *.fasta
sed -i "s/Satdi1/Saturnispora_dispora_NRRL_Y-1447/g" *.fasta
sed -i "s/Schst1/Scheffersomyces_stipitis_NRRL_Y-11545_v2.0/g" *.fasta
sed -i "s/Schpo1/Schizosaccharomyces_pombe/g" *.fasta
sed -i "s/Sclsc1/Sclerotinia_sclerotiorum_v1.0/g" *.fasta
sed -i "s/Sepmu1/Septoria_musiva_SO2202_v1.0/g" *.fasta
sed -i "s/Seppo1/Septoria_populicola_v1.0/g" *.fasta
sed -i "s/Setho1/Setomelanomma_holmii_CBS_110217_v1.0/g" *.fasta
sed -i "s/Settu1/Setosphaeria_turcica_Et28A_v2.0/g" *.fasta
sed -i "s/Sodal1/Sodiomyces_alkalinus_v1.0/g" *.fasta
sed -i "s/Sorma1/Sordaria_macrospora_k-hell/g" *.fasta
sed -i "s/Spapa1/Spathaspora_passalidarum_NRRL_Y-27907_v2.0/g" *.fasta
sed -i "s/Sphbr1/Sphaerosporella_brunnea_Sb_GMNB300_v2.0/g" *.fasta
sed -i "s/Spofi1/Sporormia_fimetaria_v1.0/g" *.fasta
sed -i "s/Stano1/Stagonospora_nodorum_SN15_v2.0/g" *.fasta
sed -i "s/Stely1/Stemphylium_lycopersici_CIDEFI-216/g" *.fasta
sed -i "s/Talbo1/Talaromyces_borbonicus_CBS_141340/g" *.fasta
sed -i "s/Talst1/Talaromyces_stipitatus_ATCC_10500/g" *.fasta
sed -i "s/Tapde1/Taphrina_deformans/g" *.fasta
sed -i "s/Ternu1/Teratosphaeria_nubilosa_CBS_116005_v1./g" *.fasta
sed -i "s/Tercl1/Terfezia_claveryi_T7_v1.0/g" *.fasta
sed -i "s/Tetph1/Tetrapisispora_phaffii_CBS_4417/g" *.fasta
sed -i "s/Thela1/Thermomyces_lanuginosus_SSBP/g" *.fasta
sed -i "s/Thite1/Thielavia_terrestris_v2.0/g" *.fasta
sed -i "s/Tirni1/Tirmania_nivea_G3_v1.0/g" *.fasta
sed -i "s/Tolin1/Tolypocladium_inflatum_NRRL_8044/g" *.fasta
sed -i "s/Torca1/Tortispora_caseinolytica_Y-17796_v1.0/g" *.fasta
sed -i "s/Torde1/Torulaspora_delbrueckii_CBS_1146/g" *.fasta
sed -i "s/Totfu1/Tothia_fuscella_CBS_130266_v1.0/g" *.fasta
sed -i "s/Trepe1/Trematosphaeria_pertusa_CBS_122368_v1.0/g" *.fasta
sed -i "s/Trire1/Trichoderma_reesei_v2.0/g" *.fasta
sed -i "s/Trihy1/Trichophaea_hybrida_UTF0779_v1.0/g" *.fasta
sed -i "s/Trive1/Trichophyton_verrucosum_HKI_0517/g" *.fasta
sed -i "s/Tubae1/Tuber_aestivum_var._urcinatum_v1.0/g" *.fasta
sed -i "s/Uncre1/Uncinocarpus_reesii_UAMH_1704/g" *.fasta
sed -i "s/Ustvi1/Ustilaginoidea_virens/g" *.fasta
sed -i "s/Vanpo1/Vanderwaltozyma_polyspora_DSM_70294/g" *.fasta
sed -i "s/Venef1/Venturia_effusa/g" *.fasta
sed -i "s/Verga1/Verruconis_gallopava/g" *.fasta
sed -i "s/Veren1/Verruculina_enalia_CBS_304.66_v1.0/g" *.fasta
sed -i "s/Veral1/Verticillium_alfalfae_VaMs.102/g" *.fasta
sed -i "s/Virvi1/Viridothelium_virens_v1.0/g" *.fasta
sed -i "s/Wesor1/Westerdykella_ornata_CBS_379.55_v1.0/g" *.fasta
sed -i "s/Wicso1/Wickerhamiella_sorbophila_DS02/g" *.fasta
sed -i "s/Wican1/Wickerhamomyces_anomalus_NRRL_Y-366-8_v1.0/g" *.fasta
sed -i "s/Wilmi1/Wilcoxina_mikolae_CBS_423.85_v1.0/g" *.fasta
sed -i "s/Yarli1/Yarrowia_lipolytica_PO1f_v1.0/g" *.fasta
sed -i "s/Zasce1/Zasmidium_cellare_ATCC_36951_v1.0/g" *.fasta
sed -i "s/Zoprh1/Zopfia_rhizophila_v1.0/g" *.fasta
sed -i "s/Zygro1/Zygosaccharomyces_rouxii_CBS732/g" *.fasta
